-- Migration 008 — ore counters
--
-- Adds ore_counts column to player_state, storing per-metal ore counters
-- as a JSON-encoded array of 9 ints (one per metal index 0..8).
--
-- Used by the new skeleton-gameplay loop: each skeleton kill drops one ore
-- of a rarity-weighted random metal (see ORE_DROP_WEIGHTS in lib/data.js),
-- and counters fill until reaching ORE_PER_BAR (10) at which point the
-- player can "Claim Coin" to roll a coin of that metal.
--
-- Vault endpoints are coded to gracefully handle this column being absent
-- (tryQuery wraps the read), so applying this migration is safe at any
-- point and won't break existing deployments before it runs.
ALTER TABLE player_state ADD COLUMN ore_counts TEXT NOT NULL DEFAULT '[0,0,0,0,0,0,0,0,0]';
